#!/usr/bin/env python
# coding: utf-8

# Generates human readable labels for IHME data column names
# Adapted on definitions provided by the IHME in their readme.txt

column_translator = {
    'date': 'Date',
    # mean
    'allbed_mean': 'All Beds Used (Mean)',
    'ICUbed_mean': 'ICU Beds Used (Mean)',
    'InvVen_mean': 'Ventilators Used (Mean)',
    'deaths_mean': 'Daily Deaths (Mean)',
    'admis_mean': 'Hospital Admissions (Mean)',
    'newICU_mean': 'New ICU Patients (Mean)',
    'totdea_mean': 'Cumulative Deaths (Mean)',
    'bedover_mean': 'All Beds Shortage (Mean)',
    'icuover_mean': 'ICU Beds Shortage (Mean)',
    # lower
    'allbed_lower': 'All Beds Used (Lower)',
    'ICUbed_lower': 'ICU Beds Used (Lower)',
    'InvVen_lower': 'Ventilators Used (Lower)',
    'deaths_lower': 'Daily Deaths (Lower)',
    'admis_lower': 'Hospital Admissions (Lower)',
    'newICU_lower': 'New ICU Patients (Lower)',
    'totdea_lower': 'Cumulative Deaths (Lower)',
    'bedover_lower': 'All Beds Shortage (Lower)',
    'icuover_lower': 'ICU Beds Shortage (Lower)',
    # upper
    'allbed_upper': 'All Beds Used (Upper)',
    'ICUbed_upper': 'ICU Beds Used (Upper)',
    'InvVen_upper': 'Ventilators Used (Upper)',
    'deaths_upper': 'Daily Deaths (Upper)',
    'admis_upper': 'Hospital Admissions (Upper)',
    'newICU_upper': 'New ICU Patients (Upper)',
    'totdea_upper': 'Cumulative Deaths (Upper)',
    'bedover_upper': 'All Beds Shortage (Upper)',
    'icuover_upper': 'ICU Beds Shortage (Upper)',
    # lanl specific columns in ihme format
    'confirmed_lower':'Cumulative Cases (Lower)',
    'confirmed_mean':'Cumulative Cases (Mean)',
    'confirmed_upper':'Cumulative Cases (Upper)',
    'daily_confirmed_lower':'Daily Cases (Lower)',
    'daily_confirmed_mean':'Daily Cases (Mean)',
    'daily_confirmed_upper':'Daily Cases (Upper)',
}

lanl_to_ihme_translator = {
    'dates':'date',
    'state':'location_name',
    'fcst_date':'model_version',
    #cumulative stats
    'deaths_q025':'totdea_lower',
    'deaths_q50':'totdea_mean',
    'deaths_q975':'totdea_upper',
    'confirmed_q025':'confirmed_lower',
    'confirmed_q50':'confirmed_mean',
    'confirmed_q975':'confirmed_upper',
    #calculated daily stats
    'deaths_q025_diff':'deaths_lower',
    'deaths_q50_diff':'deaths_mean',
    'deaths_q975_diff':'deaths_upper',
    'confirmed_q025_diff':'daily_confirmed_lower',
    'confirmed_q50_diff':'daily_confirmed_mean',
    'confirmed_q975_diff':'daily_confirmed_upper',
}

yyg_to_ihme_translator = {
    'predicted_total_infected_lower': 'confirmed_lower',
    'predicted_total_infected_mean': 'confirmed_mean',
    'predicted_total_infected_upper': 'confirmed_upper',
    'predicted_deaths_lower': 'deaths_lower',
    'predicted_deaths_mean': 'deaths_mean',
    'predicted_deaths_upper': 'deaths_upper',
    'predicted_new_infected_lower': 'daily_confirmed_lower',
    'predicted_new_infected_mean': 'daily_confirmed_mean',
    'predicted_new_infected_upper': 'daily_confirmed_upper',
    'predicted_total_deaths_lower': 'totdea_lower',
    'predicted_total_deaths_mean': 'totdea_mean',
    'predicted_total_deaths_upper': 'totdea_upper',

}

us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'American Samoa': 'AS',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Guam': 'GU',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

us_state_abbrev = {v: k for k, v in us_state_abbrev.items()}
